[workspace]
members = [
    'apfs-derive',
    'apfs-types',
    'apple-bom',
    'apple-bundles',
    'apple-codesign',
    'apple-dmg',
    'apple-flat-package',
    'apple-sdk',
    'apple-xar',
    'app-store-connect',
    'cpio-archive',
]
resolver = "2"
