[package]
name = "apple-xar"
version = "0.12.0-pre"
authors = ["Gregory Szorc <gregory.szorc@gmail.com>"]
edition = "2021"
license = "MPL-2.0"
description = "XAR archive reading and writing"
keywords = ["apple", "xar"]
homepage = "https://github.com/indygreg/apple-platform-rs"
repository = "https://github.com/indygreg/apple-platform-rs.git"
readme = "README.md"

[dependencies]
base64 = "0.20.0"
bcder = "0.7"
bzip2 = "0.4"
chrono = { version = "0.4", features = ["serde"] }
cryptographic-message-syntax = "0.18"
digest = "0.10"
log = "0.4"
md-5 = "0.10"
flate2 = "1.0"
rand = "0.8"
reqwest = { version = "0.11", default-features = false }
scroll = { version = "0.11", features = ["derive"] }
serde-xml-rs = "0.6"
serde = { version = "1.0", features = ["derive"] }
sha1 = "0.10"
sha2 = "0.10"
signature = "1.6"
thiserror = "1.0"
url = "2.3"
xml-rs = "0.8"
x509-certificate = "0.15"
xz2 = { version = "0.1", features = ["static"] }
