[package]
name = "app-store-connect"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0 OR MIT"
description = "Apple App Store Connect API and client"
keywords = ["apple"]
homepage = "https://github.com/indygreg/apple-platform-rs"
repository = "https://github.com/indygreg/apple-platform-rs.git"
readme = "README.md"

[dependencies]
anyhow = "1.0.68"
base64 = "0.20.0"
clap = { version = "4.0.32", features = ["derive"] }
dirs = "4.0.0"
env_logger = "0.10.0"
jsonwebtoken = "8.2.0"
log = "0.4.17"
pem = "1.1.0"
rand = "0.8.5"
reqwest = { version = "0.11.13", default-features = false, features = ["blocking", "json", "rustls-tls"] }
rsa = "0.7.2"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.91"
thiserror = "1.0.38"
x509-certificate = "0.17.0"
