[package]
name = "apple-flat-package"
version = "0.13.0"
authors = ["Gregory Szorc <gregory.szorc@gmail.com>"]
edition = "2021"
license = "MPL-2.0"
description = "Apple flat package (.pkg) format handling"
keywords = ["apple", "flat-package", "pkgbuild", "pkg", "productbuild"]
homepage = "https://github.com/indygreg/apple-platform-rs"
repository = "https://github.com/indygreg/apple-platform-rs.git"
readme = "README.md"

[dependencies]
flate2 = "1.0.25"
scroll = { version ="0.11.0", features = ["derive"] }
serde-xml-rs = "0.6.0"
serde = { version = "1.0.152", features = ["derive"] }
thiserror = "1.0.38"

[dependencies.apple-xar]
path = "../apple-xar"
version = "0.13.0-pre"

[dependencies.cpio-archive]
path = "../cpio-archive"
version = "0.7.0-pre"
